name: CellSePi Desktop Builds

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types: [published]
  workflow_dispatch:

env:
  PYTHON_VERSION: 3.12.8
  PYTHONUTF8: 1
  FLET_CLI_NO_RICH_OUTPUT: 1
  UV_NO_PROGRESS: 1

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Clean previous build & temp
        run: |
          df -h
          sudo rm -rf /home/runner/actions-runner/cached/_diag/*
          sudo rm -rf /home/runner/work/_temp/*
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/local/share/boost
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          sudo rm -rf /tmp/*
          rm -rf /home/runner/work/CellSePi/CellSePi/build/flutter/.dart_tool
          df -h

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          pip cache purge
          python -m pip install --upgrade pip
          pip install --no-cache-dir --only-binary :all: -r requirements.txt

      - name: Disable lazy loader for scikit-image
        run: echo "SCIKIT_IMAGE_NO_LAZY=1" >> $GITHUB_ENV

      - name: Flet Build Linux
        shell: bash
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev
          export CI=true
          flet build linux --no-rich-output

      - name: Cleanup temp dirs
        run: |
              rm -rf /home/runner/work/CellSePi/CellSePi/build/flutter/.dart_tool
              rm -rf /tmp/*
              rm -rf /home/runner/work/CellSePi/CellSePi/build/flutter/build/temp
              rm -rf /home/runner/work/CellSePi/CellSePi/build/flutter/build/cache
              df -h

      - name: Upload Linux Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-build-artifact
          path: build/linux
          if-no-files-found: warn
          overwrite: false

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          pip cache purge
          python -m pip install --upgrade pip
          pip install --no-cache-dir --only-binary :all: -r requirements.txt

      - name: Disable lazy loader for scikit-image
        run: echo "SCIKIT_IMAGE_NO_LAZY=1" >> $GITHUB_ENV

      - name: Flet Build macOS
        shell: bash
        run: |
          export CI=true
          flet build macos --no-rich-output

      - name: Upload macOS Artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-build-artifact
          path: build/macos
          if-no-files-found: warn
          overwrite: false

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        shell: pwsh
        run: |
          pip cache purge
          python -m pip install --upgrade pip
          pip install --no-cache-dir --only-binary :all: -r requirements.txt

      - name: Final Flet Build Windows
        shell: pwsh
        run: |
          $env:SCIKIT_IMAGE_NO_LAZY = "1"
          $env:CI='true'
          flet build windows --no-rich-output --source-packages skimage

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-build-artifact
          path: build/windows
          if-no-files-found: warn
          overwrite: false
