name: CellSePi Desktop Builds

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types: [published]
  workflow_dispatch:

env:
  BUILD_NUMBER: 1
  BUILD_VERSION: 0.1.0
  PYTHON_VERSION: 3.12.8
  PYTHONUTF8: 1
  FLET_CLI_NO_RICH_OUTPUT: 1
  UV_NO_PROGRESS: 1

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Clean previous build & temp
        run: |
          rm -rf build/
          sudo rm -rf /tmp/*

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Flet Build Linux
        shell: bash
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev
          export CI=true
          flet build linux --verbose --build-number=$BUILD_NUMBER --build-version=$BUILD_VERSION

      - name: Upload Linux Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-build-artifact
          path: build/linux
          if-no-files-found: warn
          overwrite: false

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Flet Build macOS
        shell: bash
        run: |
          export CI=true
          flet build macos --verbose --build-number=$BUILD_NUMBER --build-version=$BUILD_VERSION

      - name: Upload macOS Artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-build-artifact
          path: build/macos
          if-no-files-found: warn
          overwrite: false

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        shell: pwsh
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Final Flet Build Windows
        shell: pwsh
        run: |
          $env:CI='true'
          flet build windows --verbose --no-rich-output --build-number=$env:BUILD_NUMBER --build-version=$env:BUILD_VERSION

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-build-artifact
          path: build/windows
          if-no-files-found: warn
          overwrite: false
